server:
  port: 9093
spring:
  cloud:
    gateway:
      routes:
        - id: water-monitor-service
          uri: 'http://localhost:18043'
          predicates:
            - Path=/water-monitor-service/**